version: "3.8"  # 최신 버전 사용
services:

  oj-redis:
    image: redis:4.0-alpine
    container_name: oj-redis
    restart: always
    volumes:
      - /home/$(whoami)/deploy_data/redis:/data  # WSL 내 저장 위치로 변경

  oj-postgres:
    image: postgres:10-alpine
    container_name: oj-postgres
    restart: always
    volumes:
      - /home/$(whoami)/deploy_data/postgres:/var/lib/postgresql/data  # 경로 변경　$(whoami)に自分のUser名変更
    environment:
      - POSTGRES_DB=onlinejudge
      - POSTGRES_USER=onlinejudge
      - POSTGRES_PASSWORD=onlinejudge

  judge-server:
    image: onlinejudge/judge_server  # 중국 레지스트리 제거
    container_name: judge-server
    platform: linux/amd64
    restart: always
    read_only: true
    cap_drop:
      - SETPCAP
      - MKNOD
      - NET_BIND_SERVICE
      - SYS_CHROOT
      - SETFCAP
      - FSETID
    tmpfs:
      - /tmp
    volumes:
      - /home/$(whoami)/deploy_data/backend/test_case:/test_case:ro  #$(whoami)に自分のUser名変更
      - /home/$(whoami)/deploy_data/judge_server/log:/log            #$(whoami)に自分のUser名変更
      - /home/$(whoami)/deploy_data/judge_server/run:/judger         #$(whoami)に自分のUser名変更
    environment:
      - SERVICE_URL=http://judge-server:8080
      - BACKEND_URL=http://oj-backend:8000/api/judge_server_heartbeat/
      - TOKEN=CHANGE_THIS

  oj-backend:
    image: onlinejudge/oj_backend  # 중국 레지스트리 제거
    container_name: oj-backend
    platform: linux/amd64
    restart: always
    depends_on:
      - oj-redis
      - oj-postgres
      - judge-server
    volumes:
      - /home/$(whoami)/deploy_data/backend:/data              #$(whoami)に自分のUser名変更
      - /home/$(whoami)/deploy_data/backend/dist:/app/dist    #$(whoami)に自分のUser名変更
    environment:
      - POSTGRES_DB=jnajudge
      - POSTGRES_USER=jnajudge
      - POSTGRES_PASSWORD=jnajudge
      - JUDGE_SERVER_TOKEN=CHANGE_THIS
    ports:
      - "8080:8000"  # 포트 80 충돌 방지
      - "8443:1443"
